import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:kunggy_operational_app/common/widget/my_buttons/my_elevated_button.dart';
import 'package:kunggy_operational_app/common/widget/text_view.dart';
import 'package:kunggy_operational_app/theme/my_colors.dart';
import 'package:kunggy_operational_app/theme/my_text_styles.dart';
import 'package:pin_code_fields/pin_code_fields.dart';

import '../../../../l10n/app_localizations.dart';
import 'location_access_screen.dart';
import 'login_screen.dart';

class TwoFactorAuthScreen extends StatefulWidget {
  const TwoFactorAuthScreen({super.key});

  @override
  State<TwoFactorAuthScreen> createState() => _TwoFactorAuthScreenState();
}

class _TwoFactorAuthScreenState extends State<TwoFactorAuthScreen> {
  final TextEditingController _pinController = TextEditingController();
  String _currentPin = "";

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              SizedBox(height: 36.h),

              /// Back Button
              IconButton(
                icon: const Icon(Icons.arrow_back, size: 32),
                onPressed: () => Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => const LoginScreen()),
                ),
              ),

              SizedBox(height: 40.h),

              /// Title
              Center(
                child: TextView(
                  "Two-Factor\nAuthentication",
                  style: myTextStyle.font_10w400.copyWith(
                    fontSize: 26,
                    fontWeight: FontWeight.w700,
                  ),
                  textAlign: TextAlign.center,
                ),
              ),

              /// Subtitle
              Center(
                child: TextView(
                  padding: EdgeInsets.symmetric(horizontal: 28.w),
                  "Enter the six digit code generated by your authentication app.",
                  style: myTextStyle.font_10w400.copyWith(
                    fontSize: 14,
                    color: MyColors.gray6E7C87,
                  ),
                  textAlign: TextAlign.center,
                ),
              ),

              SizedBox(height: 36.h),

              /// PIN Code Fields
              Padding(
                padding: EdgeInsets.symmetric(horizontal: 34.w),
                child: PinCodeTextField(
                  appContext: context,
                  length: 6,
                  controller: _pinController,
                  onChanged: (value) {
                    setState(() {
                      _currentPin = value;
                    });
                  },
                  onCompleted: (value) {
                    // Yahan bhi navigation daal sakte hain agar auto-submit chahiye ho
                  },
                  pinTheme: PinTheme(
                    shape: PinCodeFieldShape.box,
                    borderRadius: BorderRadius.circular(10.r),
                    fieldHeight: 70.h,
                    fieldWidth: 50.w,
                    activeFillColor: MyColors.grayF7F7F8.withValues(alpha: 0.30),
                    inactiveFillColor: MyColors.grayF7F7F8.withValues(alpha: 0.30),
                    selectedFillColor: MyColors.grayF7F7F8.withValues(alpha: 0.30),
                    activeColor: MyColors.boarderE5E9EB,
                    inactiveColor: MyColors.boarderE5E9EB,
                    selectedColor: MyColors.primaryDark1D1929,
                    borderWidth: 1,
                  ),
                  enableActiveFill: true,
                  textStyle: myTextStyle.font_20wMedium.copyWith(
                    fontSize: 20.h,
                    fontWeight: FontWeight.w600,
                    color: MyColors.primaryDark1D1929,
                  ),
                  keyboardType: TextInputType.number,
                  animationType: AnimationType.fade,
                  animationDuration: const Duration(milliseconds: 300),
                ),
              ),

              SizedBox(height: 20.h),

              /// Resend Code
              Center(
                child: GestureDetector(
                  onTap: () {
                    // Handle resend code
                  },
                  child: TextView(
                    "Didn't receive code? Resend",
                    style: myTextStyle.font_10w400.copyWith(
                      fontSize: 14,
                      decoration: TextDecoration.underline,
                    ),
                  ),
                ),
              ),

              SizedBox(height: 42.h),

              /// Allow Access Button - Updated to work without condition
              MyElevatedButton(
                text: "Allow Access",
                onPressed: () {
                  // Direct navigation bina kisi check ke
                  Navigator.pushReplacement(
                    context,
                    MaterialPageRoute(
                      builder: (context) => const LocationAccessScreen(),
                    ),
                  );
                },
                padding: EdgeInsets.symmetric(horizontal: 36.w),
                height: 56,
                buttonBGColor: MyColors.primaryDark1D1929,
                textStyle: myTextStyle.font_20wMedium.copyWith(
                  fontSize: 20.h,
                  color: MyColors.whiteFFFFFF,
                ),
                borderRadius: BorderRadius.circular(12.r),
              ),

              SizedBox(height: 30.h),
            ],
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    _pinController.dispose();
    super.dispose();
  }
}